### ISSUE TITLE
Non-technical: Hazelgrove logos and iconography

### ISSUE THREAD

**Issue by matthewhammer** [hazelgrove/hazelgrove#3]
Any ideas for logos or iconography, for either Hazelnut or Hazelgrove?

Some image ideas: 
- [Hazel tree leaves and nuts](https://upload.wikimedia.org/wikipedia/commons/e/e1/Illustration_Corylus_avellana0.jpg)
- [Photo of a hazel tree grove](http://www.arkive.org/hazel/corylus-avellana/image-A9595.html)

Related: This [section from wikipedia](https://en.wikipedia.org/wiki/Hazel#Mythology_and_folklore) an interesting read, it claims: "The Celts believed hazelnuts gave one wisdom and inspiration."

**Comment by MichaelHilton** [comment]
I think it would be best to have a vectorized version, so that we could use it as a logo big and small. I will look at this when I have some more time.

**Comment by ivoysey** [comment]
I usually like the sort of downplayed line-art style logos for technical projects. They tend to look better on slides and in different coloring variants.  We should probably figure something out fairly soon so we can update the totally stock little avatar for this org.

**Comment by ivoysey** [comment]
A few draft ideas for logos in different file formats and color / greyscale are now in the new repo hazelgrove/graphics. I'm going to close this thread and we can move whatever discussion we might want to have over there.
